name: puppeteer_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  puppeteer: ^3.17.0
  # path: ^1.8.0
  shelf: ^1.4.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
